# application-secret.yml

spring:
  datasource:
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6479

  mail:
    username: wo0982@naver.com
    password: korean12@

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

oauth2:
  naver:
    client-id: 8Ho43QH9aynWnzRErDsS
    client-secret: 4pzjI6XbNz

  google:
    client-id: 746874777548-gqjqcaqq9sfqhaij1rh45rerttn6spt3.apps.googleusercontent.com
    client-secret: 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

  kakao:
    client-id: 1238518
    client-secret: ZTwwE51bi8UdBssy2dMvQ23qLvYjWlr6