# application-prod.yml

spring:
  rabbitmq:
    host: localhost
    port: 5772
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 1.5
          max-interval: 3000
        default-requeue-rejected: false

  datasource:
    url: jdbc:mysql://15.165.27.231:3306/zzirit-dev?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    # 추후 운영환경용 db docker file 작성 후 다시 prod 로 변경 예정
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6479

rabbitmq:
  queue:
    name: order.confirm.queue
    dlq-name: order.confirm.dlq
  exchange:
    name: order.confirm.exchange
    dlq-name: order.confirm.dlx
  routing:
    key: order.confirm.routing-key
    dlq-key: order.confirm.dlq-routing-key

custom:
  site:
    domain: api.zzirit.shop
    back-url: https://api.zzirit.shop
    front-url: http://localhost:3000,https://zzirit.vercel.app,https://www.app4.qwas.shop,https://login.aleph.kr,http://3.34.152.225,https://zzirit-test.vercel.app

oauth2:
  google:
    redirect-uri: https://api.zzirit.shop/login/oauth2/code/google

  kakao:
    redirect-uri: https://api.zzirit.shop/login/oauth2/code/kakao

  naver:
    redirect-uri: https://api.zzirit.shop/login/oauth2/code/naver

server:
  forward-headers-strategy: framework
